### ISSUE TITLE
Publish es2015 compliant JS

### ISSUE THREAD

**Issue by danielglasgow** [Urigo/merge-graphql-schemas#117]
This package does not appear to publish JS to NPM compiled to es2015. This causes problems with create-react-app: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

Could this package also publish es2015 JS?

**Comment by cfnelson** [comment]
@danielglasgow We already compile both a `cjs` bundle which is the `main` & a `esm` bundle which is the `module`. See the pkg json [here](https://github.com/okgrow/merge-graphql-schemas/blob/master/package.json#L12), if this is broken for you could you provide the error messages.

Additionally providing more details to the problems you are having would be helpful along with a minimally reproduction.

You can check our [RollupJS config](https://github.com/okgrow/merge-graphql-schemas/blob/master/rollup.config.js) and [Babel config](https://github.com/okgrow/merge-graphql-schemas/blob/master/.babelrc), they may need some updating/modifications. If you notice any bugs/problems with it we would be happy to accept a PR to fix the build.

**Comment by danielglasgow** [comment]
@cfnelson I will try to find time in the next week to PR a solution and/or a minimal reproduction. 

For starters though, both the `.cjs` and the `.esm` files have `Object.values` calls in them (with no polyfill). This alone will not be es2015 compliant.

**Comment by cfnelson** [comment]
@danielglasgow Ahh thank you for spotting that, If I have time this week I will also try to take a look. Out of curiosity what target environment are you trying to support? 

This package was meant to be transpiling to support `node 4.8.3`. We are thinking/planning to drop support and move to `node 6` or `node 8` as the min supported environment instead of a specific es2015, es2016, es2017 standard.

**Comment by kamilkisiela** [comment]
#196 no longer depends on polyfills
