### ISSUE TITLE
This repo is unmaintained.

### ISSUE THREAD

**Issue by pauldowman** [Urigo/merge-graphql-schemas#191]
We're not able to maintain this any more. If you would like to maintain it please let me know.  But I don't want to just transfer it to someone random, to avoid another [event-stream incident](https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident) (not that this package is anywhere near as widely used). 

If you have been contributing to this package or have other good contributions to show I'll be happy to recommend your fork.

**Comment by mmanela** [comment]
@pauldowman Thanks for all your work on this, is has been a fantastic lib. 

Do you know if there are any other alternatives to this package? I started using this since it seemed to be the only thing out there that met what I was looking for. It might be good to list some alternatives on the README for other options if people are not comfortable using a package that is no longer actively maintained.

**Comment by Urigo** [comment]
Hi Everyone!

Thanks to the great leadership of @pauldowman , we've had a conversation and The Guild would take the work of maintaining of `merge-graphql-schemas` and `graphql-scalars`.

We will release a blog post soon with more details and a roadmap.

All the great words of appreciation I have to say to @pauldowman and the amazing team from ok-grow will be written in the blog post and referenced here.

**Comment by pauldowman** [comment]
This repo is in great hands, thank you for taking it @Urigo! We couldn't have hoped for a better steward.

**Comment by Urigo** [comment]
Just released an update about what's next: https://twitter.com/UriGoldshtein/status/1141012158613991425

**Comment by RichardLitt** [comment]
@pauldowman I can't think of a better steward, either. :)
